### PR TITLE
Added C environment

### PR DESCRIPTION
**Pull request by clarkimusmax**
Added sample C environment with starter source directory, main.c, and Makefile.

### CODE REVIEW

**Comment by cbrnrd** [comment]
Thanks for contributing! One thing to change and then this will be merged: Could you move all of the data from the `c` directory into the `c.zip` folder?

The current structure is `C:/Users/Uname/c.zip/c/Makefile` when it should be `C:/Users/Uname/c.zip/Makefile`

**Comment by clarkimusmax** [comment]
> Thanks for contributing! One thing to change and then this will be merged: Could you move all of the data from the `c` directory into the `c.zip` folder?
> 
> The current structure is `C:/Users/Uname/c.zip/c/Makefile` when it should be `C:/Users/Uname/c.zip/Makefile`

Last commit should fix that.

**Comment by cbrnrd** [comment]
Great, thanks! I’ll test it in a few minutes and merge if everything goes well.

**Comment by cbrnrd** [comment]
All good! Merging now, thanks for contributing!

**Comment by cbrnrd** [comment]
Fix #3

**Pull request merged**
